@server_url = http://localhost:3050

### Create task
POST {{server_url}}/task
Content-Type: application/json

{
  "title": "Task 2",
  "description": "In this task I have another thing to do."
}

### Find all tasks
GET {{server_url}}/task

### Find one task
GET {{server_url}}/task/1bcad8f7-c8e9-4906-88ee-15311a8a6041

### Update task
PUT {{server_url}}/task/d4f5e09e-e0e9-42fd-a958-c4ed151bb36f
Content-Type: application/json

{
  "title": "Task 2",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pulvinar leo in velit auctor, nec congue sapien imperdiet. Phasellus a ultrices lorem. Suspendisse convallis aliquet augue quis condimentum. Aliquam faucibus placerat porta. Duis a nibh nunc. Sed quis enim eros. Pellentesque non dapibus ligula, a volutpat lorem. Quisque eget suscipit enim. Sed egestas finibus sagittis. Praesent ut ipsum in libero vulputate placerat vitae vitae metus. In porttitor velit vel diam tempus condimentum a in mi. Phasellus nisl neque, sodales ut diam non, commodo varius purus. Proin vulputate eget nunc a porta. Pellentesque eu semper dui. Sed auctor ut nisl eget feugiat."
}