@server_url = http://localhost:3050

### Create task
POST {{server_url}}/task
Content-Type: application/json

{
  "title": "Task 2",
  "description": "In this task I have another thing to do."
}

### Find all tasks
GET {{server_url}}/task

### Find one task
GET {{server_url}}/task/1bcad8f7-c8e9-4906-88ee-15311a8a6041